
package org.sapr.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DroneManagementService", targetNamespace = "http://webservice.sapr.org/", wsdlLocation = "http://localhost:7001/SaprBusiness/DroneManagementService?WSDL")
public class DroneManagementService
    extends Service
{

    private final static URL DRONEMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException DRONEMANAGEMENTSERVICE_EXCEPTION;
    private final static QName DRONEMANAGEMENTSERVICE_QNAME = new QName("http://webservice.sapr.org/", "DroneManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7001/SaprBusiness/DroneManagementService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DRONEMANAGEMENTSERVICE_WSDL_LOCATION = url;
        DRONEMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public DroneManagementService() {
        super(__getWsdlLocation(), DRONEMANAGEMENTSERVICE_QNAME);
    }

    public DroneManagementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DRONEMANAGEMENTSERVICE_QNAME, features);
    }

    public DroneManagementService(URL wsdlLocation) {
        super(wsdlLocation, DRONEMANAGEMENTSERVICE_QNAME);
    }

    public DroneManagementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DRONEMANAGEMENTSERVICE_QNAME, features);
    }

    public DroneManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DroneManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DroneManagement
     */
    @WebEndpoint(name = "DroneManagementPort")
    public DroneManagement getDroneManagementPort() {
        return super.getPort(new QName("http://webservice.sapr.org/", "DroneManagementPort"), DroneManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DroneManagement
     */
    @WebEndpoint(name = "DroneManagementPort")
    public DroneManagement getDroneManagementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.sapr.org/", "DroneManagementPort"), DroneManagement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DRONEMANAGEMENTSERVICE_EXCEPTION!= null) {
            throw DRONEMANAGEMENTSERVICE_EXCEPTION;
        }
        return DRONEMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
