
package org.sapr.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DroneManagement", targetNamespace = "http://webservice.sapr.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DroneManagement {


    /**
     * 
     * @return
     *     returns org.sapr.webservice.DroneResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllDrone", targetNamespace = "http://webservice.sapr.org/", className = "org.sapr.webservice.GetAllDrone")
    @ResponseWrapper(localName = "getAllDroneResponse", targetNamespace = "http://webservice.sapr.org/", className = "org.sapr.webservice.GetAllDroneResponse")
    @Action(input = "http://webservice.sapr.org/DroneManagement/getAllDroneRequest", output = "http://webservice.sapr.org/DroneManagement/getAllDroneResponse")
    public DroneResp getAllDrone();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.sapr.webservice.DroneResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteDrone", targetNamespace = "http://webservice.sapr.org/", className = "org.sapr.webservice.DeleteDrone")
    @ResponseWrapper(localName = "deleteDroneResponse", targetNamespace = "http://webservice.sapr.org/", className = "org.sapr.webservice.DeleteDroneResponse")
    @Action(input = "http://webservice.sapr.org/DroneManagement/deleteDroneRequest", output = "http://webservice.sapr.org/DroneManagement/deleteDroneResponse")
    public DroneResp deleteDrone(
        @WebParam(name = "arg0", targetNamespace = "")
        Drone arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.sapr.webservice.DroneResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertDrone", targetNamespace = "http://webservice.sapr.org/", className = "org.sapr.webservice.InsertDrone")
    @ResponseWrapper(localName = "insertDroneResponse", targetNamespace = "http://webservice.sapr.org/", className = "org.sapr.webservice.InsertDroneResponse")
    @Action(input = "http://webservice.sapr.org/DroneManagement/insertDroneRequest", output = "http://webservice.sapr.org/DroneManagement/insertDroneResponse")
    public DroneResp insertDrone(
        @WebParam(name = "arg0", targetNamespace = "")
        DroneReq arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.sapr.webservice.DroneResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateDrone", targetNamespace = "http://webservice.sapr.org/", className = "org.sapr.webservice.UpdateDrone")
    @ResponseWrapper(localName = "updateDroneResponse", targetNamespace = "http://webservice.sapr.org/", className = "org.sapr.webservice.UpdateDroneResponse")
    @Action(input = "http://webservice.sapr.org/DroneManagement/updateDroneRequest", output = "http://webservice.sapr.org/DroneManagement/updateDroneResponse")
    public DroneResp updateDrone(
        @WebParam(name = "arg0", targetNamespace = "")
        DroneReq arg0);

}
