
package org.sapr.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserManagementService", targetNamespace = "http://webservice.sapr.org/", wsdlLocation = "http://localhost:7001/SaprBusiness/UserManagementService?WSDL")
public class UserManagementService
    extends Service
{

    private final static URL USERMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERMANAGEMENTSERVICE_EXCEPTION;
    private final static QName USERMANAGEMENTSERVICE_QNAME = new QName("http://webservice.sapr.org/", "UserManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7001/SaprBusiness/UserManagementService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERMANAGEMENTSERVICE_WSDL_LOCATION = url;
        USERMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public UserManagementService() {
        super(__getWsdlLocation(), USERMANAGEMENTSERVICE_QNAME);
    }

    public UserManagementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERMANAGEMENTSERVICE_QNAME, features);
    }

    public UserManagementService(URL wsdlLocation) {
        super(wsdlLocation, USERMANAGEMENTSERVICE_QNAME);
    }

    public UserManagementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERMANAGEMENTSERVICE_QNAME, features);
    }

    public UserManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserManagement
     */
    @WebEndpoint(name = "UserManagementPort")
    public UserManagement getUserManagementPort() {
        return super.getPort(new QName("http://webservice.sapr.org/", "UserManagementPort"), UserManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserManagement
     */
    @WebEndpoint(name = "UserManagementPort")
    public UserManagement getUserManagementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.sapr.org/", "UserManagementPort"), UserManagement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERMANAGEMENTSERVICE_EXCEPTION!= null) {
            throw USERMANAGEMENTSERVICE_EXCEPTION;
        }
        return USERMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
